[project]
name = "gatsby-exp-dagster"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dagster>=1.12.3",
    "dagster-webserver>=1.12.3",
]
